using ASAP trick for codecov

diff --git a/.github/workflows/databases-ci.yaml b/.github/workflows/databases-ci.yaml
--- a/.github/workflows/databases-ci.yaml
+++ b/.github/workflows/databases-ci.yaml
@@ -51,25 +51,27 @@ jobs:
 
       - name: Install package
         # conda setup requires this special shell
-        shell: bash -l {0}
         run: |
           python -m pip install ./missense_kinase_toolkit/databases --no-deps
           micromamba list
 
       - name: Run tests
         # conda setup requires this special shell
-        shell: bash -l {0}
         run: |
-          pytest -v --cov-report=xml --color=yes  \
-          --cov=missense_kinase_toolkit/databases \
-           missense_kinase_toolkit/databases/missense_kinase_toolkit/databases/tests/test_databases.py
+          # run each package test suite; append to coverage file
+          # exit immediately if a command exits with a non-zero status
+          set -e
+          # pytest -v --cov-report=xml --color=yes  \
+          pytest -n auto --durations=10 -v --cov-report=xml --cov-report=term --color=yes \
+            --cov=missense_kinase_toolkit/databases \
+            missense_kinase_toolkit/databases/missense_kinase_toolkit/databases/tests/test_databases.py
 
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v4.0.1
         with:
           fail_ci_if_error: false # optional (default = false)
-          file: missense_kinase_toolkit/databases/coverage.xml
-          flags: databases # optional
+          file: ./coverage.xml
+          flags: unittests # optional
           name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
           # https://github.com/codecov/codecov-action
           token: ${{ secrets.CODECOV_TOKEN }} # required
