Monorepo (#53)
* added initial monorepo set-up

* added database-ci.yaml

* updated database > databases in __init__ and tool.pytest.ini_options

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* updated databases-ci.yaml for database > databases name change

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* absolute instead of relative path for databases tests

* black formatted databases sub-package

* flake8 in databases and added path to CI

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* black

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* udpated test path

* udpated test path CI

* more database > databases and specified file in tests directory

* black

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* changed --cov argument to missense_kinase_toolkit/databases directory

* changed relative to absolute reference

* --cov=databases

* specify file

* specify test Python file and remove test sub-directory

* fixed typo

* --cov=./

* removed src directory and pyproject.toml/poetry.lock from outer directory

* removed CI file

* --cov=missense_kinase_toolkit/databases

* moving test to sub-directory and --cov=./

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* install package in right directory

* flake8 for test_databases.py

* using ASAP trick for codecov

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* reverting back to shell: bash -l {0}

* removed -n auto --durations=10

* added line break to tests

* added strip to Abl sequence

* added strip to both Abl sequences

* reverted to one line Abl sequence

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* noqa E501 for Abl sequence

* removed boilerplate cookiecutter info

* moved setup.cfg to database

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* .codecov.yml updates

* changing coverage report location

* black, pyproject.toml to outer directory

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* fixing .coverage.xml location and removign direct test reference

* reverting .codecov.yml and duplicate column widths in setup.cfg

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* added __init__.py file in intermediate missense_kinase_toolkit and tests directories

* created TestDatabases class in test file

* clarified that others are for databases sub-package

* commented out tool.pytest.ini_options and tool.coverage.run options for now

* added python3 -m to pip install instructions:

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/databases-ci.yaml b/.github/workflows/databases-ci.yaml
--- a/.github/workflows/databases-ci.yaml
+++ b/.github/workflows/databases-ci.yaml
@@ -1,4 +1,4 @@
-name: CI
+name: databases-ci
 
 on:
   # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
@@ -6,9 +6,13 @@ on:
   push:
     branches:
       - "main"
+    paths:
+      - "missense_kinase_toolkit/databases/**"
   pull_request:
     branches:
       - "main"
+    paths:
+      - "missense_kinase_toolkit/databases/**"
   schedule:
     # Weekly tests run on main by default:
     #   Scheduled workflows run on the latest commit on the default or base branch.
@@ -27,9 +31,6 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      # - name: Install poetry
-      #   run: pipx install poetry
-
       - name: Additional info about the build
         shell: bash
         run: |
@@ -45,7 +46,6 @@ jobs:
           environment-name: test
           # conda-forge is the default channel now and does not need to be specified
           channels: conda-forge,defaults
-          # cache: 'poetry'
           extra-specs: |
             python=${{ matrix.python-version }}
 
@@ -53,29 +53,28 @@ jobs:
         # conda setup requires this special shell
         shell: bash -l {0}
         run: |
-          python -m pip install . --no-deps
-          # python -m pip install poetry
-          # python -m venv .venv --copies
-          # poetry config virtualenvs.create false
-          # poetry install
+          python -m pip install ./missense_kinase_toolkit/databases --no-deps
           micromamba list
 
       - name: Run tests
         # conda setup requires this special shell
         shell: bash -l {0}
         run: |
-          pytest -v --cov=missense_kinase_toolkit --cov-report=xml --color=yes tests/
-          # poetry run pytest -v --cov=missense_kinase_toolkit --cov-report=xml --color=yes tests/
+          # run each package test suite; append to coverage file
+          # exit immediately if a command exits with a non-zero status
+          set -e
+          # pytest -n auto --durations=10 -v --cov-report=xml --cov-report=term --color=yes \
+          pytest -v --cov-report=xml --color=yes  \
+            --cov=missense_kinase_toolkit/databases \
+            missense_kinase_toolkit/databases/missense_kinase_toolkit/databases/tests/
 
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v4.0.1
         with:
           fail_ci_if_error: false # optional (default = false)
           file: ./coverage.xml
-          flags: unittests # optional
+          flags: databases # optional
           name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
           # https://github.com/codecov/codecov-action
           token: ${{ secrets.CODECOV_TOKEN }} # required
           verbose: true # optional (default = false)
-        # env:
-        #   slug: choderalab/missense-kinase-toolkit
